sudo: false
language: python
python:
  - 3.6
  - 3.7
  - 3.8
matrix:
  include:
    - python: 3.7
      dist: xenial
    - python: 3.8
      dist: xenial
install:
  - pip install poetry
  - poetry install -vvv
script:
  - poetry run coverage run --source=har2postman -m pytest tests -vvv
  - poetry run coverage report
  - poetry run coveralls